spring:
  datasource:
    url: jdbc:postgresql://192.168.1.9:5432/spring_batch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        demo:
          repository: DEBUG
